remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Annie Nicole Rojas Vaughan
baseurl: '/'
url: 'https://annie-nicole.github.io'  
description: Mathematician interested in Data Science
show_downloads: false
google_analytics:

theme: jekyll-theme-hacker

theme: jekyll-theme-hacker

